### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by kiranmaya** [EpicSpaces/Reinforcement-Learning-c-sharp-Unity-ppo-ddpg-dqn#1]
Hi
I haven’t fully read all the scripts but a few, I came to understand that you implemented neural net and Rl algorithms in c#.  Does it use  Gpu for  learning weights n bias?, it not possible unless you were using compute shaders in unity.
I’m looking for c# implementation for rl to use in winforms. Will these scripts works in .net standard.

**Comment by EpicSpaces** [comment]
thanks for viewing my scripts, it is indeed an implementation of neural net and RL algorithms in C#. 
no it does not use GPU for learning, it is possible with a GPU programming framework, computer shaders are for the graphics part, GPU will do the trick but only if it there is an extended duration, like 48 hours etc ...

of course, these scripts will work perfectly in .net standard.
enjoy :)

**Comment by kiranmaya** [comment]
Ok, thanks for replay. You were one of kind to write rl in pure c# , no such exits untill now. Cheers.

**Comment by GeorgeS2019** [comment]
@EpicSpaces  You could port the PyTorch codes  to [TorchSharp ](https://github.com/dotnet/TorchSharp)(.Net6 with Cuda support)

Here is ONE example of a port of PyTorch RL to[ TorchSharp RL](https://github.com/losttech/Torch.RL)

**Comment by GeorgeS2019** [comment]
@EpicSpaces  I make the suggestion because there is so much promising what you have done. Please keep pushing and the .NET community appreciate your contribution[s].

**Comment by EpicSpaces** [comment]
sadly, there is nothing promising, especially in video games. 
For the moment, all the algorithms, here are classic, let's try something new, in the future, also it's meant to be from scratch without any library, enjoy !

**Comment by krishnanpc** [comment]
> thanks for viewing my scripts, it is indeed an implementation of neural net and RL algorithms in C#. 
> no it does not use GPU for learning, it is possible with computer shaders, they will do the trick but only if it takes long times like 48 hours etc ...
> 
> of course, these scripts will work perfectly in .net standard.
> enjoy :)

Really good work. I would like to know more about this.
You said it is do the trick if training times are long, and can be accelerated using compute shaders? 

Is it possible to do the simulation (the physics etc also) in compute shaders?

**Comment by EpicSpaces** [comment]
I meant, you don't need computer shaders only in rare cases, but if you insist you are on you're own, yes you can do the simulation (the physics etc also) in compute shaders.
