### ISSUE TITLE
Adam optimisation is called and run are the results used?

### ISSUE THREAD

**Issue by makeplayhappy** [EpicSpaces/Reinforcement-Learning-c-sharp-Unity-ppo-ddpg-dqn#2]
Hi @EpicSpaces 

thanks for this repo, I've been trying to use it at runtime and I was wondering if my reading of the code is right?

The Adam optimisations in [Matrix.cs](https://github.com/EpicSpaces/Reinforcement-Learning-c-sharp-Unity-ppo-ddpg-dqn/blob/main/Assets/Scripts/Matrix.cs#L6-L22) doesn't return any value (void) and nothing is passed by reference.

Adam is called in [ActorNet.cs](https://github.com/EpicSpaces/Reinforcement-Learning-c-sharp-Unity-ppo-ddpg-dqn/blob/main/Assets/Scripts/ActorNet.cs#L191-L196) and [CriticNet.cs](https://github.com/EpicSpaces/Reinforcement-Learning-c-sharp-Unity-ppo-ddpg-dqn/blob/main/Assets/Scripts/CriticNet.cs#L105-L108) I don't see any variables passed by ref, does the optimisation get fed back somehow?

I think the first variable in the Adam method should be passed by reference.

**Comment by EpicSpaces** [comment]
In C#, arrays are the reference types so it can be passed as arguments to the method. A method can modify the value of the elements of the array. Both single-dimensional and multidimensional arrays can be passed as an argument to the methods.

**Comment by makeplayhappy** [comment]
Ah, that was me having a blonde moment! thanks for the reply
