### ISSUE TITLE
Archive Password

### ISSUE THREAD

**Issue by Oyedoyin** [EpicSpaces/Reinforcement-Learning-c-sharp-Unity-ppo-ddpg-dqn#3]
Hello,

Thank you very much for making this! I've been trying to implement custom training in the Unity Editor for months and this might be the key I've been looking for.

Can you please help with the rar archive password?
<img width="333" alt="Screenshot 2023-08-08 at 10 17 28 PM" src="https://github.com/EpicSpaces/Reinforcement-Learning-c-sharp-Unity-ppo-ddpg-dqn/assets/73965723/09891ffa-38f3-42a9-b8a0-77fd98486fdd">

**Comment by EpicSpaces** [comment]
******...

**Comment by Oyedoyin** [comment]
Thank you very much!
